"""WhatsApp providers.

Two implementations behind one interface:

  `EvolutionGoWhatsAppProvider` - the vendored Go service (see edge/whatsapp-gateway).
      It speaks the WhatsApp Web protocol via whatsmeow, which Meta's terms prohibit.
      Numbers get banned, without warning and without a distinguishable error - the send
      simply starts failing. That is the whole reason this file has two classes.

  `CloudApiWhatsAppProvider` - Meta's official WhatsApp Business Cloud API. Not wired up
      yet (needs Business verification and template approval), but the shape is fixed here
      so switching is configuration rather than a rewrite (CLARIFICATIONS #22).

**Two keys, not one.** The gateway has two authentication modes and they are not
interchangeable:

  - The *admin* key (`GLOBAL_API_KEY`) authorises instance lifecycle: create, list, delete.
  - The *instance token* authorises everything that acts as the linked number: status, QR,
    send, logout. The gateway looks the instance up **by** this token, which is why none
    of those calls pass an instance name.

The instance token is supplied by us at creation time rather than generated by the
gateway, so it can live in configuration alongside the admin key instead of being captured
from a create response and persisted somewhere.

A ban is invisible at the API level, so a disconnected instance is classified as a
*permanent* failure with a distinct code. Marking it retryable would bury a dead
integration under a retry queue that never drains, which is exactly how alerting stops
working without anyone being told.
"""
from __future__ import annotations

import logging
import re
from typing import Any

import httpx

from csense_shared.notifications.providers import (
    Channel,
    DeliveryOutcome,
    Message,
    SendResult,
    redact,
)

logger = logging.getLogger(__name__)

REQUEST_TIMEOUT = httpx.Timeout(20.0, connect=5.0)
E164 = re.compile(r"^\+[1-9]\d{7,14}$")

# Failure codes worth surfacing to an operator, as opposed to a routine bounce.
INSTANCE_UNAVAILABLE = "whatsapp_instance_unavailable"
LICENCE_INACTIVE = "whatsapp_licence_inactive"


class _MissingInstanceToken(RuntimeError):
    """Raised internally when an instance-scoped call has no token configured.

    A distinct type so it is never mistaken for a transport error and retried - and so the
    admin key can never be sent to an instance route by accident.
    """


class EvolutionGoWhatsAppProvider:
    """Talks to the vendored WhatsApp gateway's HTTP API.

    One instance is one connected WhatsApp number. A deployment can run several; this
    provider is bound to one, identified by its token.
    """

    def __init__(
        self,
        base_url: str,
        admin_api_key: str,
        instance_token: str = "",
        instance_name: str = "default",
        *,
        client: httpx.AsyncClient | None = None,
    ) -> None:
        if not base_url or not admin_api_key:
            raise ValueError("WhatsApp gateway base URL and admin API key are required")
        self._base_url = base_url.rstrip("/")
        self._admin_api_key = admin_api_key
        # May legitimately be empty before an instance has been created; calls that need
        # it fail with a clear reason rather than falling back to the admin key.
        self._instance_token = instance_token
        self._instance_name = instance_name
        self._client = client

    @property
    def code(self) -> str:
        return "whatsapp-gateway"

    @property
    def channel(self) -> Channel:
        return Channel.WHATSAPP

    @property
    def instance_name(self) -> str:
        return self._instance_name

    def validate_recipient(self, recipient: str) -> bool:
        # E.164 only. WhatsApp silently misroutes ambiguous local formats, which looks
        # like a delivered message that nobody ever received.
        return bool(E164.match(recipient))

    async def _request(
        self, method: str, path: str, *, admin: bool = False, **kwargs
    ) -> httpx.Response:
        """Sends a request with whichever key the route requires.

        `admin=True` uses the global key (instance lifecycle); otherwise the instance
        token, which is how the gateway identifies which number is acting.
        """
        key = self._admin_api_key if admin else self._instance_token
        if not key:
            raise _MissingInstanceToken()
        headers = {"apikey": key, "Content-Type": "application/json"}
        url = f"{self._base_url}{path}"
        if self._client is not None:
            return await self._client.request(method, url, headers=headers, **kwargs)
        async with httpx.AsyncClient(timeout=REQUEST_TIMEOUT) as client:
            return await client.request(method, url, headers=headers, **kwargs)

    # --- Licence ---------------------------------------------------------------------

    async def licence_status(self) -> dict[str, Any]:
        """Whether the gateway's own vendor licence is activated.

        Evolution Go gates **every** other endpoint behind activation with Evolution
        Foundation, returning 503 until it is done. Without this check an unactivated
        gateway is indistinguishable from a broken one, and the real cause - "register
        with the vendor" - is invisible.
        """
        try:
            # /license/status sits outside the licence gate, so it answers even when the
            # rest of the API does not.
            response = await self._request("GET", "/license/status", admin=True)
        except httpx.HTTPError as exc:
            return {"activated": False, "state": "unreachable", "detail": redact(str(exc))}

        if response.status_code != 200:
            return {"activated": False, "state": "error", "detail": redact(response.text)}

        body = self._safe_json(response)
        return {
            "activated": body.get("status") == "active",
            "state": body.get("status", "unknown"),
            "instance_id": body.get("instance_id"),
        }

    async def licence_registration_url(self) -> dict[str, Any]:
        """The vendor's registration URL, so an operator can activate the licence.

        This calls Evolution Foundation's service. It is their intended activation flow,
        surfaced in our console because we do not ship their manager UI.
        """
        try:
            response = await self._request("GET", "/license/register", admin=True)
        except httpx.HTTPError as exc:
            return {"ok": False, "detail": redact(str(exc))}

        if response.status_code != 200:
            return {"ok": False, "detail": redact(response.text)}

        body = self._safe_json(response)
        return {
            "ok": True,
            "status": body.get("status"),
            "register_url": body.get("register_url"),
            "message": body.get("message"),
        }

    async def activate_licence(self, code: str) -> dict[str, Any]:
        """Exchanges an authorisation code from the vendor's registration callback."""
        try:
            response = await self._request(
                "GET", "/license/activate", admin=True, params={"code": code}
            )
        except httpx.HTTPError as exc:
            return {"ok": False, "detail": redact(str(exc))}

        body = self._safe_json(response)
        return {
            "ok": response.status_code == 200 and body.get("status") == "active",
            "status": body.get("status"),
            # Never echo the code back, and redact whatever the licensing server returned.
            "detail": redact(body.get("message") or body.get("error") or response.text),
        }

    # --- Instance lifecycle ------------------------------------------------------------

    async def create_instance(self, name: str, token: str) -> dict[str, Any]:
        """Creates an instance. Uses the admin key; linking a number is a separate QR step.

        The token is supplied rather than generated by the gateway, so it can live in
        configuration instead of being captured from this response and persisted.
        """
        try:
            response = await self._request(
                "POST", "/instance/create", admin=True, json={"name": name, "token": token}
            )
        except httpx.HTTPError as exc:
            return {"ok": False, "detail": redact(str(exc))}

        if response.status_code in (200, 201):
            return {"ok": True, "instance": name}
        # Already exists: idempotent from the console's point of view. Failing here would
        # block the QR step for no reason.
        if response.status_code == 409:
            return {"ok": True, "instance": name, "detail": "Instance already exists."}
        return {"ok": False, "detail": redact(response.text), "status_code": response.status_code}

    async def instance_status(self) -> dict[str, Any]:
        """Connection state of the WhatsApp session.

        Surfaced in the Developer Console: a disconnected instance means alerts are not
        going out, and that must be visible before someone needs them rather than
        discovered during an incident.
        """
        try:
            response = await self._request("GET", "/instance/status")
        except _MissingInstanceToken:
            return {
                "connected": False,
                "state": "not_created",
                "detail": "No instance token configured. Create an instance first.",
            }
        except httpx.HTTPError as exc:
            return {"connected": False, "state": "unreachable", "detail": redact(str(exc))}

        if response.status_code == 401:
            return {
                "connected": False,
                "state": "not_created",
                "detail": "The gateway does not recognise this instance token.",
            }
        if response.status_code != 200:
            return {"connected": False, "state": "error", "detail": redact(response.text)}

        body = self._safe_json(response)
        data = body.get("data") if isinstance(body.get("data"), dict) else body
        connected = bool(data.get("connected"))
        state = str(
            data.get("state")
            or data.get("status")
            or ("connected" if connected else "disconnected")
        ).lower()
        return {
            "connected": connected or state in ("open", "connected", "online"),
            "state": state,
            "instance": self._instance_name,
            "jid": data.get("jid") or None,
        }

    async def instance_connect(self) -> dict[str, Any]:
        """Starts a connection attempt, which is what makes a QR available."""
        try:
            response = await self._request("POST", "/instance/connect", json={})
        except _MissingInstanceToken:
            return {"ok": False, "detail": "No instance token configured."}
        except httpx.HTTPError as exc:
            return {"ok": False, "detail": redact(str(exc))}

        ok = response.status_code in (200, 201)
        return {"ok": ok, "detail": None if ok else redact(response.text)}

    async def instance_qr(self) -> dict[str, Any]:
        """Fetches the current pairing QR.

        The QR rotates every ~20 seconds, so this is polled rather than cached. Nothing is
        persisted: a captured QR is enough to link a device, so it stays in flight only.
        """
        try:
            response = await self._request("GET", "/instance/qr")
        except _MissingInstanceToken:
            return {"ok": False, "detail": "No instance token configured. Create an instance first."}
        except httpx.HTTPError as exc:
            return {"ok": False, "detail": redact(str(exc))}

        if response.status_code != 200:
            return {"ok": False, "detail": redact(response.text), "status_code": response.status_code}

        body = self._safe_json(response)
        data = body.get("data") if isinstance(body.get("data"), dict) else body
        return {
            "ok": True,
            "instance": self._instance_name,
            "qr_code": data.get("qrcode") or data.get("qr") or data.get("base64"),
            "pairing_code": data.get("pairingCode") or data.get("code"),
        }

    async def instance_logout(self) -> dict[str, Any]:
        """Unlinks the WhatsApp number. DELETE, per the gateway's routing."""
        try:
            response = await self._request("DELETE", "/instance/logout")
        except _MissingInstanceToken:
            return {
                "ok": False,
                "instance": self._instance_name,
                "detail": "No instance token configured.",
            }
        except httpx.HTTPError as exc:
            return {"ok": False, "instance": self._instance_name, "detail": redact(str(exc))}

        ok = response.status_code in (200, 204)
        return {
            "ok": ok,
            "instance": self._instance_name,
            "detail": None if ok else redact(response.text),
        }

    # --- Sending -----------------------------------------------------------------------

    async def send(self, message: Message) -> SendResult:
        if not self.validate_recipient(message.recipient):
            return SendResult(
                DeliveryOutcome.FAILED_PERMANENT,
                failure_code="invalid_recipient",
                failure_summary="Recipient is not a valid E.164 phone number.",
            )

        number = message.recipient.lstrip("+")

        # Media send when there is a snapshot, text otherwise. An intrusion alert with the
        # annotated frame attached is actionable; the same words alone are not.
        if message.media_urls:
            path = "/send/media"
            payload: dict[str, Any] = {
                "number": number,
                "url": message.media_urls[0],
                "type": "image",
                "caption": message.body,
            }
        else:
            path = "/send/text"
            payload = {"number": number, "text": message.body}

        try:
            response = await self._request("POST", path, json=payload)
        except _MissingInstanceToken:
            return SendResult(
                DeliveryOutcome.FAILED_PERMANENT,
                failure_code=INSTANCE_UNAVAILABLE,
                failure_summary="No WhatsApp instance is configured on this deployment.",
            )
        except httpx.TimeoutException as exc:
            return SendResult(
                DeliveryOutcome.FAILED_RETRYABLE,
                failure_code="timeout",
                failure_summary=redact(str(exc)),
            )
        except httpx.HTTPError as exc:
            # The gateway itself is unreachable - a deployment problem, worth retrying.
            return SendResult(
                DeliveryOutcome.FAILED_RETRYABLE,
                failure_code="gateway_unreachable",
                failure_summary=redact(str(exc)),
            )

        return self._interpret(response)

    def _interpret(self, response: httpx.Response) -> SendResult:
        summary = redact(response.text)

        if response.status_code in (200, 201):
            body = self._safe_json(response)
            data = body.get("data") if isinstance(body.get("data"), dict) else body
            key = data.get("key") if isinstance(data.get("key"), dict) else None
            message_id = (key or {}).get("id") or data.get("id") or data.get("messageId")
            return SendResult(DeliveryOutcome.ACCEPTED, provider_message_id=message_id)

        # 401 means the gateway did not recognise the instance token - the instance is
        # gone, most often because the number was banned or the linked device was removed.
        # Permanent on purpose: this needs a human to re-link, and retrying would hide it.
        if response.status_code in (401, 404, 409, 428):
            logger.error(
                "whatsapp_instance_unavailable",
                extra={"instance": self._instance_name, "status": response.status_code},
            )
            return SendResult(
                DeliveryOutcome.FAILED_PERMANENT,
                failure_code=INSTANCE_UNAVAILABLE,
                failure_summary=(
                    "WhatsApp instance is not connected or not recognised. The number may "
                    "have been banned or the linked device removed; re-link it in the console."
                ),
            )

        if response.status_code == 503:
            # The vendor licence gate. Permanent: no amount of retrying activates it.
            return SendResult(
                DeliveryOutcome.FAILED_PERMANENT,
                failure_code=LICENCE_INACTIVE,
                failure_summary=(
                    "The WhatsApp gateway licence is not activated. Activate it in the "
                    "Developer Console before WhatsApp alerts can send."
                ),
            )

        if response.status_code == 429 or response.status_code >= 500:
            return SendResult(
                DeliveryOutcome.FAILED_RETRYABLE,
                failure_code=f"gateway_{response.status_code}",
                failure_summary=summary,
            )

        return SendResult(
            DeliveryOutcome.FAILED_PERMANENT,
            failure_code=f"rejected_{response.status_code}",
            failure_summary=summary,
        )

    @staticmethod
    def _safe_json(response: httpx.Response) -> dict:
        try:
            body = response.json()
            return body if isinstance(body, dict) else {}
        except ValueError:
            return {}


class CloudApiWhatsAppProvider:
    """Meta's official WhatsApp Business Cloud API.

    Deliberately unimplemented rather than absent: it fixes the interface now, and keeps
    the migration path visible in the codebase instead of only in a decision document.

    Two things differ materially from the unofficial gateway, and both need doing before
    this can send anything:

      - Business-initiated messages outside a 24-hour customer service window must use a
        **pre-approved template**. An alert is always business-initiated, so every alert
        type needs its own approved template - free-form text will be rejected.
      - Media must be uploaded to Meta first and referenced by id; a public URL is not
        accepted the way the gateway accepts one.
    """

    def __init__(self, phone_number_id: str, access_token: str, *, api_version: str = "v21.0") -> None:
        self._phone_number_id = phone_number_id
        self._access_token = access_token
        self._api_version = api_version

    @property
    def code(self) -> str:
        return "whatsapp-cloud-api"

    @property
    def channel(self) -> Channel:
        return Channel.WHATSAPP

    def validate_recipient(self, recipient: str) -> bool:
        return bool(E164.match(recipient))

    async def send(self, message: Message) -> SendResult:  # pragma: no cover - not wired
        raise NotImplementedError(
            "WhatsApp Cloud API provider is not implemented yet. It requires Meta Business "
            "verification and approved message templates - see CLARIFICATIONS #22."
        )
