#!/usr/bin/env bash
# Generates local-development-only secrets: JWT RS256 keypair + random passwords.
# Never run this pattern against production — production secrets belong in a managed
# secret store (TRD-SEC-003), not generated by a shell script into local files.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SECRETS_DIR="$ROOT_DIR/infra/secrets"
ENV_FILE="$ROOT_DIR/.env"
ENV_EXAMPLE="$ROOT_DIR/.env.example"

mkdir -p "$SECRETS_DIR"

# This repo's mingw64 openssl build mishandles MSYS-style paths (/c/Users/...) when a
# path segment contains an apostrophe — it silently fails to open the output file. Give
# openssl a Windows-style path instead (via cygpath, when available) to avoid that.
if command -v cygpath >/dev/null 2>&1; then
  win_secrets_dir="$(cygpath -m "$SECRETS_DIR")"
else
  win_secrets_dir="$SECRETS_DIR"
fi

if [ ! -f "$SECRETS_DIR/jwt_private.pem" ]; then
  echo "Generating JWT RS256 keypair..."
  openssl genrsa -out "$win_secrets_dir/jwt_private.pem" 2048
  openssl rsa -in "$win_secrets_dir/jwt_private.pem" -pubout -out "$win_secrets_dir/jwt_public.pem"
else
  echo "JWT keypair already exists, skipping."
fi

rand() { openssl rand -hex 24; }

if [ ! -f "$ENV_FILE" ]; then
  echo "Creating .env from .env.example..."
  cp "$ENV_EXAMPLE" "$ENV_FILE"
  # Use PowerShell-safe sed replacements
  sed -i "s#^POSTGRES_PASSWORD=.*#POSTGRES_PASSWORD=$(rand)#" "$ENV_FILE"
  sed -i "s#^POSTGRES_API_PASSWORD=.*#POSTGRES_API_PASSWORD=$(rand)#" "$ENV_FILE"
  sed -i "s#^POSTGRES_PLATFORM_API_PASSWORD=.*#POSTGRES_PLATFORM_API_PASSWORD=$(rand)#" "$ENV_FILE"
  sed -i "s#^MONGO_PASSWORD=.*#MONGO_PASSWORD=$(rand)#" "$ENV_FILE"
  sed -i "s#^REDIS_PASSWORD=.*#REDIS_PASSWORD=$(rand)#" "$ENV_FILE"
  sed -i "s#^MINIO_ROOT_PASSWORD=.*#MINIO_ROOT_PASSWORD=$(rand)#" "$ENV_FILE"
  echo ".env created with generated passwords."
else
  echo ".env already exists, leaving passwords untouched."
fi

echo "Done. Secrets are in $SECRETS_DIR and .env (both git-ignored)."
